services:
  reverse-proxy:
    image: traefik:v3.2.3
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
    # HTTP Port
      - "80:80"
    # Web UI Port (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
    #For Traefik can Listen Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  personal-homepage:
    image: ghcr.io/mdm17/personal-homepage:latest
    labels:
      - "traefik.http.routers.personal-homepage.rule=Host(`mdm17.my.id`)"