services:
  reverse-proxy:
    image: traefik:v3.2.3
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=diky.maulana88@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
    # HTTP Port
      - "80:80"
      - "443:443"
    # Web UI Port (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
    #For Traefik can Listen Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  personal-homepage:
    image: ghcr.io/mdm17/personal-homepage:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.personal-homepage.rule=Host(`mdm17.my.id`)"
      - "traefik.http.routers.guestbook.entrypoints=websecure"
      - "traefik.http.routers.guestbook.tls.certresolver=myresolver"
volumes:
  letsencrypt: